export type Plot = {
  id?: string;
  name: string;
  farmId?: string;
  customerId?: string;
  externalId: string;
  hectare: string;
  geoJson: GeoJSON.FeatureCollection;
  createdAt?: string;
  updatedAt?: string;
  deletedAt?: string | null;
  status?: 'PENDING' | 'COMPLETED' | 'CANCELLED';
  derivedStatus?: 'PENDING' | 'IN_PROGRESS' | 'COMPLETED';
  completedAt?: string | null;
  completedBy?: string | null;
  effectiveAppliedHectares?: string;
  grossAppliedHectares?: string;
  coveragePercent?: string;
  registeredAreaHectares?: string;
  realAppliedHectares?: string;
  accountedAreaHectares?: string;
  realCoveragePercent?: string;
  accountedCoveragePercent?: string;
  applicationsCount?: number;
};
