CREATE INDEX "application_service_order_id_index" ON "applications" USING btree ("service_order_id");--> statement-breakpoint
CREATE INDEX "application_pilot_id_index" ON "applications" USING btree ("pilot_id");--> statement-breakpoint
CREATE INDEX "application_assistant_id_index" ON "applications" USING btree ("assistant_id");--> statement-breakpoint
CREATE INDEX "application_drone_id_index" ON "applications" USING btree ("drone_id");--> statement-breakpoint
CREATE INDEX "application_culture_id_index" ON "applications" USING btree ("culture_id");--> statement-breakpoint
CREATE INDEX "application_product_id_index" ON "applications" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "application_plot_id_index" ON "applications" USING btree ("plot_id");--> statement-breakpoint
CREATE INDEX "application_date_index" ON "applications" USING btree ("date");--> statement-breakpoint
CREATE INDEX "assistant_name_index" ON "assistants" USING btree ("name");--> statement-breakpoint
CREATE INDEX "contract_customer_id_index" ON "contracts" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "contract_name_index" ON "contracts" USING btree ("name");--> statement-breakpoint
CREATE INDEX "contract_date_start_index" ON "contracts" USING btree ("date_start");--> statement-breakpoint
CREATE INDEX "contract_date_end_index" ON "contracts" USING btree ("date_end");--> statement-breakpoint
CREATE INDEX "culture_type_name_index" ON "culture_types" USING btree ("name");--> statement-breakpoint
CREATE INDEX "customer_cnpj_index" ON "customers" USING btree ("cnpj");--> statement-breakpoint
CREATE INDEX "customer_name_index" ON "customers" USING btree ("name");--> statement-breakpoint
CREATE INDEX "customer_phone_index" ON "customers" USING btree ("phone");--> statement-breakpoint
CREATE INDEX "drone_name_index" ON "drones" USING btree ("name");--> statement-breakpoint
CREATE INDEX "drone_aircraft_rid_index" ON "drones" USING btree ("aircraft_rid");--> statement-breakpoint
CREATE INDEX "drone_model_index" ON "drones" USING btree ("model");--> statement-breakpoint
CREATE INDEX "farm_customer_id_index" ON "farms" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "farm_name_index" ON "farms" USING btree ("name");--> statement-breakpoint
CREATE INDEX "plot_farm_id_index" ON "plots" USING btree ("farm_id");--> statement-breakpoint
CREATE INDEX "plot_customer_id_index" ON "plots" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "plot_name_index" ON "plots" USING btree ("name");--> statement-breakpoint
CREATE INDEX "plot_external_id_index" ON "plots" USING btree ("external_id");--> statement-breakpoint
CREATE INDEX "product_name_index" ON "products" USING btree ("name");--> statement-breakpoint
CREATE INDEX "service_order_farm_service_order_id_index" ON "service_order_farms" USING btree ("service_order_id");--> statement-breakpoint
CREATE INDEX "service_order_farm_farm_id_index" ON "service_order_farms" USING btree ("farm_id");--> statement-breakpoint
CREATE INDEX "service_order_pilot_service_order_id_index" ON "service_order_pilots" USING btree ("service_order_id");--> statement-breakpoint
CREATE INDEX "service_order_pilot_pilot_id_index" ON "service_order_pilots" USING btree ("pilot_id");--> statement-breakpoint
CREATE INDEX "service_order_plot_service_order_id_index" ON "service_order_plots" USING btree ("service_order_id");--> statement-breakpoint
CREATE INDEX "service_order_plot_plot_id_index" ON "service_order_plots" USING btree ("plot_id");--> statement-breakpoint
CREATE INDEX "service_order_customer_id_index" ON "service_orders" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "service_order_contract_id_index" ON "service_orders" USING btree ("contract_id");--> statement-breakpoint
CREATE INDEX "service_order_status_index" ON "service_orders" USING btree ("status");--> statement-breakpoint
CREATE INDEX "service_order_planned_date_index" ON "service_orders" USING btree ("planned_date");--> statement-breakpoint
CREATE INDEX "service_order_number_index" ON "service_orders" USING btree ("number");